from django.db import models
from django.contrib.auth.models import User

# Create your models here.
def get_file_name(intext,filename):
    ext = filename.split(".")[-1]
class UserDetails(models.Model):
    full_name = models.CharField(max_length=200,null=True,default="dummy")
    father_name = models.CharField(max_length=200,null=True,default="dummy")
    mother_name = models.CharField(max_length=200,null=True,default="dummy")
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=1,default="dummy")
    nation = models.CharField(max_length=10,default="dummy")
    category = models.CharField(max_length=10,default="dummy")
    phys = models.CharField(max_length=1,default="dummy")
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=12,default="dummy")
    perma_addr = models.TextField(max_length=400,default="dummy")
    corres_addr = models.TextField(max_length=400,default="dummy")
    submitt = models.CharField(max_length=2)
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username
    image = models.ImageField(upload_to='images')
    signature = models.ImageField(upload_to='signatures')
    ereceipt = models.CharField(max_length=40)
    dop = models.DateField()
    gate_status = models.IntegerField()
    gate_exam = models.CharField(max_length=4)
    gate_disc = models.CharField(max_length=20)
    gate_regis = models.CharField(max_length=100)
    gate_rank = models.CharField(max_length=20)
    score_card = models.ImageField(upload_to='scores')
    quali_degree = models.CharField(max_length=200)
    univ_name = models.CharField(max_length=200)
    year_passing = models.CharField(max_length=5)
    status_deg = models.CharField(max_length=100)
    aggre_per = models.CharField(max_length=5)
    stu_status = models.CharField(max_length=200)
    fin_status = models.CharField(max_length=200)
    disc_choice1 = models.CharField(max_length=200)
    disc_choice2 = models.CharField(max_length=200)
    disc_choice3 = models.CharField(max_length=200)
    disc_choice4 = models.CharField(max_length=200)
    disc_choice5 = models.CharField(max_length=200)
    spec_choice1 = models.CharField(max_length=200)
    spec_choice2 = models.CharField(max_length=200)
    spec_choice3 = models.CharField(max_length=200)
    work_exp = models.CharField(max_length=200)
    period_from = models.CharField(max_length=200)
    period_to = models.CharField(max_length=200)
    work_org = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    pulica_status = models.CharField(max_length=200)
    publica = models.CharField(max_length=200)
    refree1_name = models.CharField(max_length=200)
    refree2_name = models.CharField(max_length=200)
    refree1_email = models.CharField(max_length=200)
    refree2_email = models.CharField(max_length=200)
    saved = models.CharField(max_length=200)
    registered = models.CharField(max_length=200)
