from django.db import models
from django.contrib.auth.models import User

# Create your models here.
def get_file_name(intext,filename):
    ext = filename.split(".")[-1]
class UserDetails(models.Model):
    full_name = models.CharField(max_length=200,null=True,blank=True)
    father_name = models.CharField(max_length=200,null=True,blank=True)
    mother_name = models.CharField(max_length=200,null=True,blank=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=1,blank=True)
    nation = models.CharField(max_length=10,blank=True)
    category = models.CharField(max_length=10,blank=True)
    phys = models.CharField(max_length=1,blank=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=12,blank=True)
    perma_addr = models.TextField(max_length=400,blank=True)
    corres_addr = models.TextField(max_length=400,blank=True)
    submitt = models.CharField(max_length=2,default="N")
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username
    image = models.ImageField(upload_to='images')
    signature = models.ImageField(upload_to='signatures')
    ereceipt = models.CharField(max_length=40)
    dop = models.DateField(null=True)
    gate_status = models.IntegerField(default=0)
    gate_exam = models.CharField(max_length=4,default="yes")
    gate_disc = models.CharField(max_length=20,blank=True)
    gate_regis = models.CharField(max_length=100,blank=True)
    gate_rank = models.CharField(max_length=20,blank=True)
    score_card = models.ImageField(upload_to='scores')
    quali_degree = models.CharField(max_length=200,blank=True)
    univ_name = models.CharField(max_length=200,blank=True)
    year_passing = models.CharField(max_length=5,blank=True)
    status_deg = models.CharField(max_length=100,blank=True)
    aggre_per = models.CharField(max_length=5,blank=True)
    stu_status = models.CharField(max_length=200,blank=True)
    fin_status = models.CharField(max_length=200,blank=True)
    disc_choice1 = models.CharField(max_length=200,blank=True)
    disc_choice2 = models.CharField(max_length=200,blank=True)
    disc_choice3 = models.CharField(max_length=200,blank=True)
    disc_choice4 = models.CharField(max_length=200,blank=True)
    disc_choice5 = models.CharField(max_length=200,blank=True)
    spec_choice1 = models.CharField(max_length=200,blank=True)
    spec_choice2 = models.CharField(max_length=200,blank=True)
    spec_choice3 = models.CharField(max_length=200,blank=True)
    work_exp = models.CharField(max_length=200,blank=True)
    period_from = models.CharField(max_length=200,blank=True)
    period_to = models.CharField(max_length=200,blank=True)
    work_org = models.CharField(max_length=200,blank=True)
    position = models.CharField(max_length=200,blank=True)
    pulica_status = models.CharField(max_length=200,blank=True)
    publica = models.CharField(max_length=200,blank=True)
    refree1_name = models.CharField(max_length=200,blank=True)
    refree2_name = models.CharField(max_length=200,blank=True)
    refree1_email = models.CharField(max_length=200,blank=True)
    refree2_email = models.CharField(max_length=200,blank=True)
    saved = models.CharField(max_length=200,blank=True)
    saved2 = models.CharField(max_length=200,blank=True)
    registered = models.CharField(max_length=200,blank=True)
