__author__ = 'zeroonehacker'

from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import datetime
import os.path
data = {'user':'user','gate_status':'gate_status','gate_exam':'gate_exam','dop':'dop','ereceipt':'34','gender':'gender','phys':'phys','mobile':'mobile','full_name':'full_name','mother_name':'mother_name','father_name':'father_name','nation':'nation','email':'email','dob':'dob','gender':'gender','category':'GEN',}
logo = os.path.join(os.path.dirname(os.path.abspath(__file__)),'logo.jpg')
lola ={"name":"dummy","roll":"dummy","air":"dummy","email":"dummy","ptype":"dummy","branch":"dummy","choice1":"dummy","choice2":"dummy","spi1":"","choice3":"dummy","choice4":"dummy","choice5":"dummy"}
mapping = {}
def pdf_gen(pdf_file,data=data,user_p=""):
    home =  (os.path.dirname(os.path.dirname(__file__)))+'/static/images/'
    print home
    logo = os.path.join(home,'logo.jpg')
    emblem = os.path.join(home,'emblem.jpg')
    pdf_file.drawImage(logo,0.6*inch,10.26*inch,width=1.2*inch,height=1.2*inch)
    pdf_file.drawImage(emblem,1.8*inch,10.26*inch,width=6.0*inch,height=1.2*inch)
    now = datetime.datetime.now()
    #pdf_file = canvas.Canvas("Branch_Change_Form.pdf")
    #pdf_file.rect(0.4*inch,9.7*inch,7.37*inch,0.3*inch)

    pdf_file.setFont('Times-Bold',12)

    pdf_file.drawCentredString(4.1*inch,9.78*inch,"PhD ADMISSIONS FOR SESSION 2015-16")
    pdf_file.setFont('Courier',12)
    pdf_file.drawString(4.23*inch,9.32*inch,"Application no. : ")
    text_object4 = pdf_file.beginText(2.4*inch,8.2*inch)
    text_object4.setFont('Times-Bold',10)
    text_object4.textLine(data["full_name"])
    text_object4.textLine(data["mother_name"])
    text_object4.textLine(data["father_name"])
    text_object4.textLine(str(data["dob"]))
    text_object4.textLine(data["email"])
    text_object4.textLine(data["nation"])
    text_object4.textLine("")
    text_object4.textLine(data["mobile"])
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(6.0*inch,9.32*inch,data['user'])
    pdf_file.drawString(6.2*inch,7.54*inch,data['gender'])
    pdf_file.drawString(6.2*inch,7.38*inch,data['category'])
    pdf_file.drawString(3.2*inch,7.2*inch,data['phys'])
    if data['category']=='GEN' or data['category']=='OBC':
        pdf_file.drawString(2.4*inch,5.14*inch,'500')
    else:
        pdf_file.drawString(2.4*inch,5.14*inch,'200')
    pdf_file.drawString(2.4*inch,4.96*inch,str(data['dop']))
    pdf_file.drawString(6.8*inch,5.14*inch,data['ereceipt'])
    pdf_file.drawString(3.4*inch,4.2*inch,str(data['gate_status']))
    pdf_file.drawString(6.7*inch,4.2*inch,data['gate_exam'])
    pdf_file.drawString(3.4*inch,4.04*inch,data['gate_disc'])
    pdf_file.drawString(3.4*inch,3.9*inch,data['gate_rank'])
    pdf_file.drawString(6.9*inch,4.04*inch,data['gate_regis'])
    pdf_file.drawString(3.4*inch,3.16*inch,data['quali_degree'])
    pdf_file.drawString(3.4*inch,3.00*inch,data['univ_name'])
    pdf_file.drawString(3.4*inch,2.82*inch,data['year_passing'])
    pdf_file.drawString(7.4*inch,2.82*inch,data['status_deg'])
    pdf_file.drawString(6.3*inch,2.65*inch,data['aggre_per'])
    pdf_file.drawString(3.4*inch,2.1*inch,data['work_exp'])
    pdf_file.drawString(3.4*inch,1.95*inch,str(data['period_from']))
    pdf_file.drawString(7.0*inch,1.95*inch,str(data['period_to']))
    pdf_file.drawString(3.4*inch,1.8*inch,data['work_org'])
    pdf_file.drawString(3.4*inch,1.65*inch,data['position'])
    pdf_file.drawString(3.4*inch,0.86*inch,data['pulica_status'])
    pdf_file.drawString(3.4*inch,0.69*inch,data['publica'])
    logo =  (os.path.dirname(os.path.dirname(__file__)))+'/static/images/uploads/'+'1'+user_p+'.jpg'
    pdf_file.drawImage(logo,6.2*inch,8.0*inch,width=1.2*inch,height=1.2*inch)
    pdf_file.drawText(text_object4)
    text_object1 = pdf_file.beginText(0.4*inch,8.6*inch)
    text_object1.setFont('Courier',10)
    pdf_file.line(0.1*inch,10.0*inch,9.6*inch,10.0*inch)
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("Personal Information ")
    text_object1.textLine("")
    text_object1.setFont('Courier',10)
    text_object1.textLine("1. FULL NAME : " )
    text_object1.textLine("2. MOTHER's NAME : ")
    text_object1.textLine("3. FATHER's NAME : " )
    text_object1.textLine("4. Date of Birth : " )
    text_object1.textLine("5. Email :                                            6. Gender : ")
    text_object1.textLine("7. Nationality :                                      8. Category : ")
    text_object1.textLine("9. Physically Challenged ? : ")
    text_object1.textLine("10. Mobile Number : " )
    text_object1.textLine("11. Permanent Address :                              12. Address for Correspondence:" )
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.textLine("")
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("Application Fee Details ")
    text_object1.textLine("")
    text_object1.setFont('Courier',10)
    text_object1.textLine("13. Application Fee :                                14. E-receipt no. : " )
    text_object1.textLine("15. Date of Payment : " )
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("")
    text_object1.textLine("Qualifying entrance exam GATE/UGC-CSIR-NET details : ")
    text_object1.textLine("")
    text_object1.setFont('Courier',10)
    text_object1.textLine("16. Are you GATE/NET qualified? :                    17. Name of the Exam : ")
    text_object1.textLine("18. GATE Exam discipline :                           19. GATE registration no. ")
    text_object1.textLine("20. GATE Rank : ")
    text_object1.textLine("")
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("Qualifying degree details : ")
    text_object1.textLine("")
    text_object1.setFont('Courier',10)
    text_object1.textLine("21. Qualifying degree : ")
    text_object1.textLine("22. University name :  ")
    text_object1.textLine("23. Year of passing/appearing :                   24. Status of Qualifying Degree : ")
    text_object1.textLine("25. Aggregate percentage or Grade point average of Qualifying degree : ")
    text_object1.setFont('Courier',10)
    text_object1.textLine("")
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("Work Experience(If applying under sponsored category)")
    text_object1.setFont('Courier',10)
    text_object1.textLine("26. Do you have work experience? : ")
    text_object1.textLine("27. Period from :                                    28. Period to :")
    text_object1.textLine("29. Name of organization : ")
    text_object1.textLine("30. Position : ")
    text_object1.setFont('Courier-Bold',12)
    text_object1.textLine("")
    text_object1.textLine("Publications : ")
    text_object1.textLine("")
    text_object1.setFont('Courier',10)
    text_object1.textLine("31. Do you have any publications? : ")
    text_object1.textLine("32. Number of publications : ")
    pdf_file.drawText(text_object1)
    pdf_file.showPage()
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(3.2*inch,10.8*inch,data['refree1_name'])
    pdf_file.drawString(3.2*inch,10.64*inch,data['refree1_email'])
    pdf_file.drawString(3.2*inch,10.48*inch,data['refree2_name'])
    pdf_file.drawString(3.2*inch,10.32*inch,data['refree2_email'])
    pdf_file.drawString(3.2*inch,9.8*inch,'PhD')
    pdf_file.drawString(3.2*inch,9.62*inch,'(HL: Humanities and Social Sciences')
    pdf_file.drawString(3.2*inch,9.44*inch,data['disc_choice1'])
    pdf_file.drawString(3.2*inch,9.28*inch,data['disc_choice2'])
    pdf_file.drawString(3.2*inch,9.12*inch,data['disc_choice3'])
    pdf_file.drawString(3.2*inch,8.94*inch,data['disc_choice4'])
    pdf_file.drawString(3.2*inch,8.78*inch,data['disc_choice5'])
    pdf_file.drawString(4.1*inch,8.42*inch,data['spec_choice1'])
    pdf_file.drawString(4.1*inch,8.26*inch,data['spec_choice2'])
    pdf_file.drawString(4.1*inch,8.10*inch,data['spec_choice3'])
    jhola = home =  (os.path.dirname(os.path.dirname(__file__)))+'/static/images/uploads/'+'2'+user_p+'.jpg'
    pdf_file.drawImage(jhola,6.0*inch,6.0*inch,width=2.0*inch,height=0.5*inch)
    pdf_file.drawString(6.4*inch,5.6*inch,"Candidate signature")
    text_object2 = pdf_file.beginText(0.4*inch,11.0*inch)
    text_object2.setFont('Courier-Bold',12)
    text_object2.textLine("Referee's Details : ")
    text_object2.setFont('Courier',10)
    text_object2.textLine("33. Name of referee 1 : ")
    text_object2.textLine("34. Email ID of referee 1 : ")
    text_object2.textLine("35. Name of referee 2 :")
    text_object2.textLine("36. Email ID of referee 2 : ")
    text_object2.textLine("")
    text_object2.setFont('Courier-Bold',12)
    text_object2.textLine("Program selection : ")
    text_object2.setFont('Courier',10)
    text_object2.textLine("37. Degree : ")
    text_object2.textLine("38. Department : ")
    text_object2.textLine("39. Discipline Choice 1 :")
    text_object2.textLine("40. Discipline choice 2 :")
    text_object2.textLine("41. Discipline choice 3 :")
    text_object2.textLine("42. Discipline choice 4 :")
    text_object2.textLine("43. Discipline choice 5 :")
    text_object2.textLine("")
    text_object2.textLine("44. Specialization Choice 1(optional) : ")
    text_object2.textLine("45. Specialization Choice 2(optional) : ")
    text_object2.textLine("46. Specialization Choice 3(optional) : ")
    pdf_file.drawText(text_object2)
    pdf_file.setDash([])
    pdf_file.line(0.2*inch,7.4*inch,8.0*inch,7.4*inch)
    text_object5 = pdf_file.beginText(0.4*inch,7.3*inch)
    text_object5.textLine("I declare that the information provided by me on this application form is correct to the ")
    text_object5.textLine("best of my knowledge and belief. I understand that any wilful misinterpretation of facts will ")
    text_object5.textLine("result in my disqualification and dismissal from the Institute if admitted.")
    pdf_file.drawText(text_object5)
    pdf_file.setFont('Courier',10)
    text_object3 = pdf_file.beginText(5.6*inch,6.05*inch)
    text_object3.setFont('Courier',10)
    pdf_file.setFont('Times-Bold',10)
    pdf_file.setFont('Courier',8)
    pdf_file.showPage()
    pdf_file.save()
    return
#if __name__=='__main__':
    #pdf_file = canvas.Canvas('Discipline_Change_Form.pdf')
    #pdf_gen(pdf_file)
